<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class ReturnShippingCostTypeEnum
{
    const C_INSURANCE = 'INSURANCE'; #Indicates the shipping cost is the price of shipping insurance if it used to return ship the item back to the seller.
    const C_LABEL_COST = 'LABEL_COST'; #Indicates the shipping cost is the price of the shipping label to return the item to the seller.
    const C_OTHER = 'OTHER'; #Indicates the shipping cost is not classified or is not known.
    const C_SIGNATURE_CONFIRMATION_COST = 'SIGNATURE_CONFIRMATION_COST'; #Indicates the shipping cost is the price to return ship the item to the seller using certified shipping.
}
